alarm:
  locationChangeCheckIntervalSeconds: 30
  automaticAlarmToggleIntervalSeconds: 60
database:
  host: localhost
  port: 4306
  showQueries: false
influxdb:
  host: localhost
  port: 8086
  database: smarthome
heater:
  intervalSeconds: 30
  maxMeasurements: 48
temperature:
  maxMeasurements: 24
  intervalSeconds: 30
raspsonar:
  maxMeasurements: 24
  intervalSeconds: 30
  autoToggleRelayIntervalSeconds: 30
  wrongMeasurementThreshold: 10
well-pump:
  intervalSeconds: 30
rain-gauge:
  intervalSeconds: 30
  maxMeasurements: 24
humidity:
  maxMeasurements: 24
  intervalSeconds: 30
  wrongMeasurementThreshold: 20
inverter:
  intervalSeconds: 30