alarm:
  locationChangeCheckIntervalSeconds: 30
database:
  host: 192.168.99.100
  port: 4306
  showQueries: true
temperature:
  maxMeasurements: 24
  intervalSeconds: 600
raspsonar:
  maxMeasurements: 24
  intervalSeconds: 600
