alarm:
  locationChangeCheckIntervalSeconds: 120
  automaticAlarmToggleIntervalSeconds: 240
database:
  host: smarthome-db
  port: 3306
  showQueries: false
influxdb:
  host: influxdb
  port: 8086
  database: smarthome
temperature:
  maxMeasurements: 24
  intervalSeconds: 7200 # 2 hours
raspsonar:
  maxMeasurements: 24
  intervalSeconds: 7200 # 2 hours
  autoToggleRelayIntervalSeconds: 30
  wrongMeasurementThreshold: 10
well-pump:
  intervalSeconds: 300
rain-gauge:
  intervalSeconds: 7200 # 2 hours
  maxMeasurements: 24
humidity:
  intervalSeconds: 7200 # 2 hours
  maxMeasurements: 24
  wrongMeasurementThreshold: 40