alarm:
  locationChangeCheckIntervalSeconds: 120
  automaticAlarmToggleIntervalSeconds: 240
database:
  host: smarthome-db
  port: 3306
  showQueries: false
temperature:
  maxMeasurements: 24
  intervalSeconds: 7200
raspsonar:
  maxMeasurements: 24
  intervalSeconds: 7200
  autoToggleRelayIntervalSeconds: 30
  wrongMeasurementThreshold: 10
well-pump:
  intervalSeconds: 300